### ISSUE TITLE
Suggested versioning

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#108]
Hi, I appreciate move esos project from svn to git, but I see problem with versioning. I think that will be better to use git tags to identify releases.

Good dev workflow provides "git flow" project http://danielkummer.github.io/git-flow-cheatsheet/

master brach - production release
develop - branch for development

Instead of complex git flow we can use just github function "Create new release" https://help.github.com/articles/creating-releases/

version naming:
1.0.1. 1.1.1, 1.2.1 and so on for releases
1.0.2, 1.0.3, 1.0.4 and so on for hotfixes

**Comment by msmith626** [comment]
Hi,

Yes, this is coming, although we'll be a little bit different in that "master" will be our development branch as we'll likely have several different "production" branches instead of just one (eg, 0.1.x-stable, 0.6.x-stable, 1.1.x-stable, etc.). I'm preparing a project update email and will create the first stable branch soon. Hopefully see something by early next week.


--Marc
