### ISSUE TITLE
Pacemaker ocf syntax error

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#118]
Hi, I try latest master build and I got these errors:

/usr/lib/ocf/resource.d/heartbeat/.ocf-shellfuncs: line 767: syntax error: bad substitution
ERROR: ocf:heartbeat:controld: could not parse meta-data:

So something is bad with resource agents :(

**Comment by msmith626** [comment]
Looking at that file I see this function:
ocf_is_bash4() {                                               
        echo "$SHELL" | grep bash > /dev/null &&            
                        [ ${BASH_VERSINFO[0]} = "4" ]          
}

If I run the last part with bash its fine; if I run 'sh' giving me an interactive Bourne shell, I get this:
# [ ${BASH_VERSINFO[0]} = "4" ]
sh: syntax error: bad substitution

So it seems the script is being run with /bin/sh instead of /bin/bash and that might be the problem? But it shouldn't even get to that since SHELL shouldn't be equal to "/bin/bash" (the && should prevent getting to the second part if SHELL was set properly for /bin/sh).

I'll look after to track it down and see what the right fix should be... setting SHELL for /bin/sh to the correct value, or should this script be being called with bash somewhere instead of /bin/sh? Looking at my Fedora system I get this:
$ ls -ltr /bin/sh
lrwxrwxrwx. 1 root root 4 Dec 30 14:30 /bin/sh -> bash

In ESOS /bin/sh is actually a different binary... maybe many of these shell scripts expect /bin/sh to actually be /bin/bash? I need to think about the fix for this for a bit, but you could probably work-around it by remove /bin/sh and adding a sym link for /bin/sh to /bin/bash like my Fedora system.

Let me know how it goes.


--Marc

**Comment by msmith626** [comment]
Did you have a chance to try switching /bin/sh for a sym link to /bin/bash?
I'm curious how this works on your system, I'm also curious what other
Linux distros besides Fedora do? Do you know how others do it?


--Marc

**Comment by feldsam** [comment]
Hi, /bin/sh is pointing to busybox, so I try to symlink it to /bin/bash and it's working now :)

**Comment by msmith626** [comment]
I'd like your thoughts/opinion on making this change global for ESOS? Like
I said before, Fedora does this. Do other Linux distros? Do you have
another non-Fedora machine around to take a peek?

--Marc

**Comment by msmith626** [comment]
[marc.smith@cumberland ~]$ ls -ltr /bin/sh
lrwxrwxrwx 1 root root 4 Oct  1  2014 /bin/sh -> bash
[marc.smith@cumberland ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 5.11 (Tikanga)

An old RHEL 5 machine does it this way too.

**Comment by feldsam** [comment]
Debian 7
lrwxrwxrwx 1 root root 4 Oct  6  2013 /bin/sh -> bash

Centos 7
lrwxrwxrwx. 1 root root 4 May  3 12:38 /bin/sh -> bash

/bin/sh symlink setup default shell, http://superuser.com/a/590193

In debian 7 is new shell "dash", but many folks change it to bash, so I think that is safe to link /bin/sh to /bin/bash.

**Comment by msmith626** [comment]
Okay, this has been fixed... committed/pushed to master. Latest image package has posted to the downloads area too.

--Marc
