### ISSUE TITLE
Unable to build stable/master with emulex support

### ISSUE THREAD

**Issue by stuarthopkins** [astersmith/esos#163]
I've been trying to build both the stable/master branches  (cloned yesterday) with the Emulex FC support but unfortunately neither works (a different error for each). I've attached build logs for each (ran as -j1 to make them easier to follow).

System: Ubuntu 12.04.5 (clean install)
OCS Ver: ocs_sdk_10.6.248.0.tgz

[build-stable-emulex-fail.txt](https://github.com/astersmith/esos/files/35388/build-stable-emulex-fail.txt)
[build-master-emulex-fail.txt](https://github.com/astersmith/esos/files/35389/build-master-emulex-fail.txt)

**Comment by msmith626** [comment]
Hi Stuart,

I looked at both error logs, and for the stable branch it appears the
module builds fine, its just a license incompatibility issue with only the
"debug" kernel:
FATAL: modpost: GPL-incompatible module ocs_fc_scst.ko uses GPL-only symbol
'lockdep_init_map'

I believe this is due to the CONFIG_LOCKDEP kernel option that is used in
the ESOS debug kernel (a somewhat recent change).

For the error with the master branch, looks like kernel version 4.1.x may
not be supported by Emulex/Avago yet. I'll look into this more, but will
probably be better to wait for Emulex to support this.

I'm working on this issue now and should have a patch you can test with
shortly.


--Marc

**Comment by msmith626** [comment]
This has been fixed in the 0.1.x branch as release 0.1.6 (version). If you'd like an image package that includes OCS SDK that I built, email me: msmith626 at gmail.com

--Marc
